name: Build CI(release)

on:
 workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      
      - name: Setup java
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@main
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build With Gradle
        run: ./gradlew assembleRelease --parallel

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: ModMenu
          path: app/*
